version: '3'
services:
  app:
    image: ghcr.io/beheadedstraw/tubular:dev
    container_name: tubular
    restart: always
    ports:
      - 8000:8000
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - CONFIG_DIR=/data
      - DOWNLOAD_DIR=/videos
    volumes:
      - /tublular/config:/data
      - /tublular/videos:/videos
